function solver = chooseSolverNN(self, method)
% SOLVER = CHOOSESOLVERNN(METHOD)
%
switch method
    case {'getAvgChainTable', 'getAvgTputTable', 'getAvgRespTTable', ...
          'getAvgUtilTable',  'getAvgSysTable', 'getAvgNodeTable', ...
          'getAvgTable', 'getAvg', 'getAvgChain', 'getAvgSys', ...
          'getAvgNode', 'getAvgArvRChain', 'getAvgQLenChain', ...
          'getAvgUtilChain', 'getAvgRespTChain', 'getAvgTputChain', ...
          'getAvgSysRespT', 'getAvgSysTput'}
        solver = chooseAvgSolverNN(self);
    case {'getTranAvg'}
        line_error(mfilename,'No chooseSolverAI method available for Transient metrics. ');
end
end